# backend/docker-compose.yml
version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://nandagopal2708:u4RrbgPO2LMN2iyu@cluster0.cdlvvfj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=secret
      - COMPILER_API_URL=http://compiler-container:8000
      - NEXT_PUBLIC_CLIENT_URL=https://oj-project-rhbi.vercel.app
    volumes:
      - .:/app
    depends_on:
      - compiler
  compiler:
    image: my-compiler:latest # Replace with your compiler image name
    ports:
      - "8000:8000"
    environment:
      - COMPILER_API_URL=http://compiler-container:8000
    volumes:
      - /path/to/compiler:/app # Adjust to your compiler's volume path